# Site settings
title: Lauren Lo
email: lo.lauren91@gmail.com
description: "Hi, I'm Lauren, a designer based in Seattle, WA. Currently, I am designing Designing with Data experiences for the Modern Worker across Office 365 at Microsoft."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hello-lalo.github.io" # the base hostname & protocol for your site
ga: UA-45562731-1

# Build settings
markdown: kramdown

# Permalinks
permalink: none

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Custom collection
collections:
  work:
    output: true
